### ISSUE TITLE
Node red crash when data fetching fails  Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by hotNipi** [zinen/node-red-contrib-nordpool-api-plus#6]
In case of data tried to fetch but internet connection is down (many possible reason for that), the errors are not handled and this ends of node-red server crash.

There is no way to catch those errors in node-red, must be done at node level somehow.

Node-red log after crash:

Trace: Error: connect ETIMEDOUT xx.xxx.x.xx:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xx.xxx.x.xx',
  port: 80
}
    at Request._callback (C:\Users\endele\.node-red\node_modules\nordpool\lib\prices.js:89:15)
    at self.callback (C:\Users\endele\.node-red\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (C:\Users\endele\.node-red\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
12 Nov 15:36:49 - [red] Uncaught Exception:
12 Nov 15:36:49 - TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\endele\.node-red\node_modules\nordpool\lib\prices.js:92:21)
    at self.callback (C:\Users\endele\.node-red\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (C:\Users\endele\.node-red\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by zinen** [comment]
Yes indeed this happens to me also.  It looks like a problem from the nordpool API. But I added a check for acces the resources of the API before requesting the API. Problem should be fixed i version 4.1.3.
Could you confirm it fixes it for you?

**Comment by hotNipi** [comment]
I will try tomorrow

**Comment by hotNipi** [comment]
Yeah. It is much better now. 
The thing you probably can't fix from node-s perspective is if client is situated behind proxy. 
I think dns resolves but query gets timeout and that is not handled in API. 
But I'm not an expert on this area so take my words not so seriously.
The dns trick does help if there is zero chance to resolve.

You can close the issue freely cos you did your best and it is fine for me also.
Thank you

**Comment by zinen** [comment]
I completely agree on the caveats of this fix. But it was quick and did not require to include more npm modules.
Both the fix and the caveats can be read on [stackoverflow](https://stackoverflow.com/a/15271685/10599784) where i got the fix.

Any other PR to fix this in a better way will be appreciated 😄

**Comment by zinen** [comment]
For the sake of history note that the changes made to fix this was somewhat reverted when bumped `nordpool` to v2.1.0 5afc733dac2183ebd1024d136a54bf7c574f43a0
